name: Netlify workflow
on:
 push:
  branches: [develop]
jobs:
 build:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node: [10.x, 12.x] 
  steps:
   - name: Setup node
     uses: actions/setup-node@v1
     with: 
      node-version: ${{matrix.node}}

   - name: Checkout
     uses: actions/checkout@v2

   - name: Setup cache
     uses: actions/cache@v1
     with:
      path: ~/.npm
      key: ${{runner.os}}-modules-${{hashFiles('**/package-lock.json') }}
      restore-keys: |
       ${{runner.os}}-modules-
       ${{runner.os}}-
   - name: Install
     run: npm ci
   - name: Lint
     run: npm run lint
   - name: Build
     run: npm run build
   - name: Deploy
     uses: netlify/actions/cli@master
     env:
      NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
      NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
     with: 
      args: deploy --dir=build --prod